pdevice/device/urls.py
from django.urls import path
from . import views

app_name = 'device'

urlpatterns = [
    path('', views.index, name='device-index'),
    # path('<int:device_id>/detail/', views.detail, name='detail'),
    path('<int:pk>/',
         views.DeviceDetailView.as_view(), name='device-detail'),
    path('new/',
         views.DeviceCreateView.as_view(), name='device-create'),
    path('<int:pk>/update/',
         views.DeviceUpdateView.as_view(), name='device-update'),
    path('<int:pk>/delete',
         views.DeviceDeleteView.as_view(), name='device-delete'),
    path('sample/', views.sample, name='device-sample'),
    path('home2/', views.HomePageView.as_view(), name='device-home2'),
    path('home3/', views.DevicePageView.as_view(), name='device-home3'),
    path('java/', views.javatest, name='java'),
    path('datetime/', views.datepick2, name='datepick'),
    path('datetime/post', views.get_datepick2, name='get_datepick2'),
    path('display/', views.display_date, name='display'),
]

pdevice/pdevice/urls.py
from django.contrib import admin
from django.urls import path, include

from . import views


urlpatterns = [
    path('', views.home, name='home'),
    path('admin/', admin.site.urls),
    path('device/', include('device.urls')),

]

pdevice/device/models.py
from django.db import models
from django.utils import timezone
# from django.utils.translation import gettext_lazy as _
from django.contrib.auth.models import User
from django.urls import reverse


class Device(models.Model):
    aid = models.CharField(max_length=20)
    name = models.CharField(max_length=100)
    lat = models.CharField(max_length=10)
    lon = models.CharField(max_length=10)
    city = models.CharField(max_length=30)
    serial = models.CharField(max_length=20)
    operated = models.DateField(blank=True, null=True, default='yyyy-mm-dd')
    # operated = models.DateField(_("yyyy-mm-dd"),
    # blank=True, null=True)
    # note = models.TextField(max_length=1000)
    # author = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.aid

    def get_absolute_url(self):
        return reverse("device:device-detail", kwargs={"pk": self.pk})

# Create your models here.

pdevice/device/forms.py
from django import forms
from models import Device
from .core.widgets import XDSoftDateTimePickerInput


class OperatedForm(forms.ModelForm):
    # operated = forms.DateInput(format="%d-%m-%Y")
    class Meta:
        model = Device
        field = '__all__'
        operated = forms.DateField(
            widget=forms.DateInput(format="%d-%m-%Y"),
            input_formats=('%d-%m-%Y', )
        )


class DateForm(forms.Form):
    date = forms.DateTimeField(
        input_formats=['%d/%m/%Y %H:%M'],
        widgets=XDSoftDateTimePickerInput())


class DateInput(forms.DateInput):
    input_type = 'date'


class ExampleForm(forms.Form):
    my_date_field = forms.DateField(widget=DateInput)

class ExampleModelForm(forms.Form):
    class Meta:
        widgets = {'my_date_field': DateInput()}

pdevice/device/views.py
import datetime
from .models import Device
from django.template import loader
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.shortcuts import get_list_or_404, render, redirect
from django.urls import reverse
from django.views.generic.base import TemplateView
from django.views.generic import (
    ListView, DetailView, CreateView, UpdateView, DeleteView)
from django.views.generic.edit import ModelFormMixin, CreateView
from django.contrib.auth.mixins import LoginRequiredMixin
import jsonpickle

from bootstrap_datepicker_plus import DateTimePickerInput
# Create your views here.


def index(request):
    recent_device = Device.objects.order_by('operated')[:20]
    context = {
        'recent_device': recent_device
    }
    return render(request, 'index.html', context)


def javatest(request):
    device = Device.objects.order_by('operated')[5]
    districts = [{'name': 'Dong Da'},
                 {'name': 'Ba Dinh'},
                 {'name': 'Hoan Kiem'}

                 ]
    # context = {
    #     'device': jsonpickle.encode(device)
    # }
    context = {
        'device': districts
    }
    # print(device.name)
    return render(request, 'javatest.html', context)


def datepick(request):
    print('reach datepick request')
    return render(request, 'datetimepicker.html')


def get_datepick2(request):
    print(request.method)
    if request.method == 'post':
        date_dict = request.POST.dict()
        print(f'Request data: {date_dict}')
        # print(request.POST.get['start'])
        # print(request.POST.get['end'])
        return HttpResponse('This is a POST REQUEST')
    print('reach end request')
    return render(request, 'datetimepicker.html')


def display_date(request, start=0, end=0):
    context = {
        'start': start,
        'end': end
    }
    return render(request, 'displaydate.html', context)

def datepick2(request):
    print(request.method)
    if request.method == 'POST':
        data = request.POST.dict()
        try:
            start_ = datetime.datetime.strptime(
                data['start'], '%Y-%m-%d').date()
            end_ = datetime.datetime.strptime(data['end'], '%Y-%m-%d').date()
            print(data)
            # return HttpResponse(f'This is a POST REQUEST with {start_} and {end_}')
        except Exception as e:
            print(f'Error as {e}')
            return HttpResponse(f'Date is not understood {data}')
    print('reach datepick 2 request')
    return redirect('display')
    # return render(request, 'datefield.html')


def detail(request, device_id):
    # text = f'Requesting detail for device {device_id}'
    # return HttpResponse(f'<h1> {text} </h1>')
    try:
        device = Device.objects.get(pk=device_id)
    except Device.DoesNotExist:
        raise Http404("Device does not existed")

    return render(request, 'detail.html', {'device': device})


def update(request, device_id):
    try:
        device = Device.objects.get(pk=device_id)
    except Device.DoesNotExist:
        raise Http404("Device does not existed")

    return render(request, 'detail.html', {'device': device})


def sample(request):
    return render(request, 'bail.html')

# Edit a post
# def edit(request, pk, template_name='Crud/edit.html'):
#     post= get_object_or_404(Post, pk=pk)
#     form = PostForm(request.POST or None, instance=post)
#     if form.is_valid():
#         form.save()
#         return redirect('index')
#     return render(request, template_name, {'form':form})


class CreateView(CreateView):
    model = Device
    fields = '__all__'

    def get_form(self):
        form = super().get_form()
        form.fields['operated'] = DateTimePickerInput()
        return form


def PostListView(ListView):
    model = Device
    template = 'device/index.html'
    context_of_name = 'devices'
    ordering = ['-updated']


class HomePageView(TemplateView):

    template_name = "index.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['recent_device'] = Device.objects.all()[:5]
        return context


class DevicePageView(ListView):

    model = Device
    template_name = 'index.html'
    context_object_name = 'recent_device'
    ordering = ['-operated']


class DeviceDetailView(DetailView):

    model = Device
    template_name = 'detail.html'


class DeviceCreateView(CreateView):

    model = Device
    fields = "__all__"
    template_name = 'form.html'

    def get_form(self):
        form = super().get_form()
        form.fields['operated'] = DateTimePickerInput()
        return form

    def form_valid(self, form):
        # form.instance.author = self.request.user
        return super().form_valid(form)


class DeviceUpdateView(UpdateView):

    model = Device
    fields = "__all__"
    template_name = 'form.html'

    def get_form(self):
        form = super().get_form()
        form.fields['operated'].wiget = DateTimePickerInput()
        return form

    def form_valid(self, form):
        # form.instance.author = self.request.user
        return super().form_valid(form)


class DeviceDeleteView(DeleteView):

    model = Device
    success_url = '/device'
    fields = "__all__"
    template_name = 'delete.html'

    def form_valid(self, form):
        # form.instance.author = self.request.user
        return super().form_valid(form)

pdevice/pdevice/views.py
from django.urls import path
from django.shortcuts import HttpResponse

def home(request):
    return HttpResponse('<h2>Main page: Under Construction</h2>')

pdevice/device/templates/bail.html
{% extends 'base_note.html' %}

{% block content %}

<h1>This is the render template</h1>
<h2>It only used for testing end route</h2>

{% endblock content %}

pdevice/device/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    {% block head %}
    <!-- Font Awesome -->
    <!-- <link rel="stylesheet" href="{% static 'css/all.css' %}" /> -->
    <!-- Bootstrap -->
    <!-- <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}" /> -->
    <!-- Custom -->
    <!-- <link rel="stylesheet" href="{% static 'css/style.css' %}" /> -->
    <link
      rel="stylesheet"
      href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
      integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
      crossorigin="anonymous"
    />

    {% block moreScripts %}
    {% endblock moreScripts %}

    {% endblock %}

    <title>Device Management</title>
  </head>

  <body>
    <!-- NavBar -->

    <!-- Main Content -->
    {% block content %}
    <!-- Footer -->

    <!-- <script src="{% static 'js/jquery-3.3.1.min.js' %} "></script> -->
    <!-- <script src="{% static 'js/bootstrap.bundle.min.js' %} "></script> -->
    <!-- <script src="{% static 'js/main.js' %} "></script> -->
    <script
      src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
      integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
      integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
      integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
      crossorigin="anonymous"
    ></script>
    {% endblock %}
  </body>
</html>

pdevice/device/templates/base_note.html
<!doctype html>
{% load static %}
{% load l10n %}
{% load crispy_forms_tags %}
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <!-- Google Font -->
    <link href="https://fonts.googleapis.com/css?family=Poppins" rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.css" type="text/css" media="all" />
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.20/css/dataTables.bootstrap4.min.css">
    <link rel="stylesheet" href="https://unpkg.com/easymde/dist/easymde.min.css">
    <link rel="stylesheet" href="{% static 'css/tagsinput.css' %}">
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
    <link rel="shortcut icon" href="{% static 'img/logo.png' %}">
    <title>{% block title %}{% endblock %}</title>
  </head>
  <body style="font-family: 'Poppins', sans-serif;">
    {% include 'navbar.html' %}   
    <div class="container-fluid h-100">
      <div class="row">
        <div class="col-lg-3 col-md-3 d-none d-lg-block d-md-block position-fixed h-100" style="background-color: #f5f5f5; padding-top: 1%;">
          <div>
            <h3>Notes <a id="a_d" class="btn float-right" style="font-size: 25px; color: blue; padding-top: 0;"  data-toggle="modal" data-target="#add_note"><i class="fas fa-plus" data-toggle="tooltip" title="Add a new note"></i></a></h3>
            <input type="text" id="search_note" class="form-control" placeholder="Search">
            </div>
            <hr>
            <ul class="nav nav-pills flex-column">
              {% for note in notes %}
              <li class="nav-item" id="note_details">
                <a href="{% url 'note_detail' note.slug %}" class="{% add_active request 'note_detail' note.slug %} nav-link"><span style="text-decoration: none !important;">{{ note.note_title|truncatechars:24 }}</a>
              </li>
              {% endfor %}
            </ul>
        </div>
        <div class="col-lg-9 col-md-9 offset-md-3 col-sm-12 col-xs-12" style="padding-top: 1%; padding-left: 0; padding-right: 0;">
          {% block content %}
          {% endblock %}
        </div>
      </div>
    </div>

    <div class="edit-modal-div"></div>
    <div class="delete-modal-div"></div>

    <!-- Add Modal -->
    <div class="modal fade" id="add_note">
      <div class="modal-dialog modal-lg">
        <div class="modal-content">

          <!-- Modal Header -->
          <div class="modal-header">
            <h4 class="modal-title">Add New Note</h4>
            <button type="button" class="close" data-dismiss="modal">&times;</button>
          </div>

          <!-- Modal body -->
          <form action="{% url 'notes' %}" method="post">
          {% csrf_token %}
          <div class="modal-body">
            <div class="row">
              {{ add_note_form.media }}
              {% for field in add_note_form %}
              <div class="form-group col-lg-12 col-md-12">
                  {{ field | as_crispy_field }}
              </div>
              {% endfor %}
            </div>
          </div>

          <!-- Modal footer -->
          <div class="modal-footer">
            <input type="submit" class="btn btn-success" value="Add">
            <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
          </div>
          </form>

        </div>
      </div>
    </div>

    <!-- Loader Div -->
    <div class="loader"></div>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.js" type="text/javascript"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.20/js/dataTables.bootstrap4.min.js"></script>
    <script src="https://unpkg.com/easymde/dist/easymde.min.js"></script>
    <script src="{% static 'js/tagsinput.js' %}"></script>
    {% block javascript %}
    {% endblock %}
  </body>
</html>

pdevice/device/templates/datefield.html
{% load crispy_forms_tags %} 
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>Date Field Experiment</title>
  </head>
  <body>
    <div style="text-align: center; margin-top: 100px">
      <h2>Date Picker</h2>
      <!-- <input type="date" /> -->

      {{ example_form.my_date_field }}
      <p>Intended as a blank line</p>
      <form method="POST">
        {% csrf_token %}
        <input name="start" type="date" />
        <input name="end" type="date" />
        <button type="submit">Post</button>
      </form>
    </div>
  </body>
</html>

pdevice/device/templates/datetimepicker.html
{% extends 'base.html' %}


{% block moreScripts %}
<script
src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
crossorigin="anonymous"
></script>

<!-- XDSoft DateTimePicker -->
<link
rel="stylesheet"
href="https://cdnjs.cloudflare.com/ajax/libs/jquery-datetimepicker/2.5.20/jquery.datetimepicker.min.css"
integrity="sha256-DOS9W6NR+NFe1fUhEE0PGKY/fubbUCnOfTje2JMDw3Y="
crossorigin="anonymous"
/>
<script
src="https://cdnjs.cloudflare.com/ajax/libs/jquery-datetimepicker/2.5.20/jquery.datetimepicker.full.min.js"
integrity="sha256-FEqEelWI3WouFOo2VWP/uJfs1y8KJ++FLh2Lbqc8SJk="
crossorigin="anonymous"
></script>
    
{% endblock moreScripts %}
{{ form.date }}

{% block content %}
<div class='container-fluid'></div>
<h1>Date Time Picker</h1>
    

<input id="id_date" type="text">
<script>
    $(function () {
      $("#id_date").datetimepicker({
        format: 'd/m/Y H:i',
      });
    });
  </script>
{% endblock content %}
    

pdevice/device/templates/delete.html
{% extends 'base.html' %}

{% block content %}
<div>
    <form method="post">
        {% csrf_token %}
        <h2>Are you sure to delete?</h2>
        <h3> Station: {{device.name}}</h3>
        <button type="submit">Yes, Delete</button>
        <a  href="{% url 'device:device-detail' device.id %}">Cancel</a>
    </form>
</div>
<div>
    <h2><a href="{% url 'device:device-index' %}">Index Page</a></h2>
</div>


{% endblock content %}

pdevice/device/templates/detail.html
{% extends 'base.html' %} {% block content %}
<div class="container">
  <h1>Details</h1>
  <h3>Name: {{device.name}}</h3>
  <h3>Primary Key: {{device.pk}}</h3>
  <h3>ID (ordering): {{device.id}}</h3>
  <h3>Arduino: {{device.aid}}</h3>
  <li>City: {{device.city}}</li>
  <li>Latitude: {{device.lon}}</li>
  <li>Longtitude: {{device.lat}}</li>
  <li>Operated from: {{device.operated}}</li>
</div>
<div class="container">
  <h2><a href="{% url 'device:device-index' %}">Index Page</a></h2>
  <h2><a href="{% url 'device:device-update' device.pk %}">Update</a></h2>
  <h2><a href="{% url 'device:device-delete' device.pk %}">Delete</a></h2>
</div>

{% endblock content %}

pdevice/device/templates/displaydate.html
{% extends 'base.html' %}
{% block content %}
<div class="container-fluid w-50 p-3">
  <h1>{{start}}</h1>
  <h2>{{end}}</h2>
</div>

{% endblock content %}

pdevice/device/templates/form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %} 
    <!-- XDSoft DateTimePicker -->
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/jquery-datetimepicker/2.5.20/jquery.datetimepicker.min.css"
      integrity="sha256-DOS9W6NR+NFe1fUhEE0PGKY/fubbUCnOfTje2JMDw3Y="
      crossorigin="anonymous"
    />
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/jquery-datetimepicker/2.5.20/jquery.datetimepicker.full.min.js"
      integrity="sha256-FEqEelWI3WouFOo2VWP/uJfs1y8KJ++FLh2Lbqc8SJk="
      crossorigin="anonymous"
    ></script>


{% block content %} 



{% load bootstrap4 %} 
{% bootstrap_css %} 
{% bootstrap_javascript jquery='full' %}
{{ form.media }}
<div class='container-fluid w-50 p-3'>
  <form method="post">  {% csrf_token %}
    <h2>Add new device</h2>
    <!-- {% bootstrap_form form %}  -->
    {{ form.as_table }}
    {% buttons %}
    <button type="submit" class="btn btn-primary">Save</button>
    {% endbuttons %}
    <!-- <button type="submit">Submit</button> -->
  </form>
</div>
<div class='container-fluid w-50 p-3'>
  <p>Place holder for datetime picker</p>
  <input id="id_date" type="text" />
</div>
<script>
  $(function() {
    $("#id_date").datetimepicker({
      format: "d/m/Y H:i"
    });
  });
</script>
{% endblock content %}

pdevice/device/templates/index.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
  {% for device in recent_device %}
  <ul>
    <a href="{% url 'device:device-detail' device.pk %}">{{device.name}}</a>
  </ul>

  {% endfor %}
</div>

{% endblock content %}

pdevice/device/templates/javatest.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>Java Test</title>

    <!-- Bootstrap 4 -->
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css"
      integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS"
      crossorigin="anonymous"
    />
    <script
      src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
      integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"
      integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"
      integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k"
      crossorigin="anonymous"
    ></script>
    <!-- Font Awesome -->
    <link
      href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
      rel="stylesheet"
      integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN"
      crossorigin="anonymous"
    />

    <!-- Moment.js -->
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.23.0/moment.min.js"
      integrity="sha256-VBLiveTKyUZMEzJd6z2mhfxIqz3ZATCuVMawPZGzIfA="
      crossorigin="anonymous"
    ></script>
      <!-- Tempus Dominus Bootstrap 4 -->
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.1.2/css/tempusdominus-bootstrap-4.min.css" integrity="sha256-XPTBwC3SBoWHSmKasAk01c08M6sIA5gF5+sRxqak2Qs=" crossorigin="anonymous" />
      <script src="https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.1.2/js/tempusdominus-bootstrap-4.min.js" integrity="sha256-z0oKYg6xiLq3yJGsp/LsY9XykbweQlHl42jHv2XTBz4=" crossorigin="anonymous"></script>
  
    </head>
    <body>
  
      <div class="input-group date" id="datetimepicker1" data-target-input="nearest">
        <input type="text" class="form-control datetimepicker-input" data-target="#datetimepicker1"/>
        <div class="input-group-append" data-target="#datetimepicker1" data-toggle="datetimepicker">
          <div class="input-group-text"><i class="fa fa-calendar"></i></div>
        </div>
      </div>
  
      <script>
        $(function () {
          $("#datetimepicker1").datetimepicker();
        });
      </script>
  
    </body>
  </html>
  
  </head>
  <body>
    <header>JS Crash</header>
    <h1>
      This is the header of plain page.
    </h1>
    <h3></h3>
    <!-- <h2 id="name">Station:</h2>
    <h2 id="name2">In the script</h2> -->
    <div id="station_holder"></div>
    <button
      type="button"
      onclick='document.getElementById("name").innerHTML = "Station Name!"'
    >
      Click Me!
    </button>
    <div
      class="input-group date"
      id="datetimepicker1"
      data-target-input="nearest"
    >
      <input
        type="text"
        class="form-control datetimepicker-input"
        data-target="#datetimepicker1"
      />
      <div
        class="input-group-append"
        data-target="#datetimepicker1"
        data-toggle="datetimepicker"
      >
        <div class="input-group-text"><i class="fa fa-calendar"></i></div>
      </div>
    </div>

    <script>
      var stations = "{{device | escapejs}}";
      <!-- var stations = ['a', 'b', 'c'] -->
      console.log(`Station: ${stations}`);

      var str = "<ul>";
      stations.forEach(function(station) {
        str += "<li>" + station + "</li>";
      });

      str += "</ul>";
      document.getElementById("station_holder").innerHTML = str;


      <!-- document.getElementById("name2").innerHTML = my_station; -->
    </script>
    <script>
      $(function() {
        $("#datetimepicker1").datetimepicker();
      });
    </script>
  </body>
</html>

pdevice/device/templates/new_device.html
<!-- file: polls/templates/polls/question_form.html -->
{% load bootstrap4 %}
{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}
{{ form.media }}

<form method="post">{% csrf_token %}
  {% bootstrap_form form %}
  <input type="submit" value="Save">
</form>

pdevice/device/templates/update.html
{% extends 'base.html' %} {% block content %} {% load bootstrap4 %} 
{%bootstrap_css %} 
{% bootstrap_javascript jquery='full' %} 
{{ form.OperatedForm }}
<div class="container">
  <h1>Update View</h1>
  <h1>Details</h1>
  <h3>Name: {{device.name}}</h3>
  <h3>Primary Key: {{device.pk}}</h3>
  <h3>Arduino: {{device.aid}}</h3>
  <li>City: {{device.city}}</li>
  <li>Latitude: {{device.lon}}</li>
  <li>Longtitude: {{device.lat}}</li>
  <li>Operated from: {{device.operated}}</li>
</div>

{% endblock content %}

pdevice/device/templates/widgets/xdsoft_datetimepicker.html
{% include "django/forms/widgets/input.html" %}
{{ form.date }}

<script>
  $(function() {
    $("input[name='{{ widget.name }}']").datetimepicker({
      format: "d/m/Y H:i"
    });
  });
</script>